4754 Remove duplicate indexes in Land DB
Beyond-Finance/land pull request #31
Opened 2023-05-26 20:07 UTC by alexGrandolph

Trello card: [Remove duplicate indexes in Land DB](https://trello.com/c/FPfvq4aG/4754-remove-duplicate-indexes-in-land-db)

2023-06-01 19:36 UTC, stevenskim requested changes
There is a typo, can you fix and reapply to update structure.sql? This change will require ADR pre to be updated as well.

2023-06-01 19:36 UTC, stevenskim commented on db/migrate/20230526200145_remove_ad_type_index_on_attributions.rb
> +    remove_index 'land.attribtions', column: :ad_type_id if index_exists?('land.attribtions', :ad_type_id)
Typo attributions is missing u

2023-06-02 13:36 UTC, stevenskim approved these changes
👍

2023-06-08 16:24 UTC, bethanymuir commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove duplicate indexes in Land DB](https://trello.com/c/FPfvq4aG/4754-remove-duplicate-indexes-in-land-db)

2023-06-08 16:49 UTC, merged